### ISSUE TITLE
does not inject tweaks

### ISSUE THREAD

**Issue by DumbGameMaker** [Al4ise/Azule#100]
Satella2 tweak gets extracted but not injected

edit: note i am 100% using satella2 for educational purposes...

**Comment by Al4ise** [comment]
yeah idc if you are into cracking. Soo, from what I saw, satella's dylibs don't target specific apps, but rather system stuffs. Ig you can try extracting the deb yourself and giving azule just the dylibs, but I can nearly guarantee a tweak like that would never work jailed

**Comment by DumbGameMaker** [comment]
Satella has a SatellaJailed script which appears to use azule internally. That seemed to work for me, i think satella is a little more involved
