### ISSUE TITLE
tutorial how to decrypt apps with azule

### ISSUE THREAD

**Issue by binnichtaktiv** [Al4ise/Azule#105]
Hi its me again😂
I just saw that you can now somehow decrypt Apps with azule but i dont know how to use it and what arguments i have to type in and how i can specify the app i want to decrypt
Btw azule can download and decrypt the app or do i have to have the app on my phone?

**Comment by Al4ise** [comment]
azule -i [bundle id of app you want to decrypt] -o [output directory]

Bundle id should look smth like 'com.google.ios.youtube' (the bundleid of youtube)

And no, you don't need to have the app installed

**Comment by gyke69** [comment]
> azule -i [bundle id of app you want to decrypt] -o [output directory]
> 
> Bundle id should look smth like 'com.google.ios.youtube' (the bundleid of youtube)
> 
> And no, you don't need to have the app installed

How do we decrypt  apps for iOS 15 and 16 since there is no jailbreak available.

**Comment by Al4ise** [comment]
You'll need a jailbroken phone on whatever OS. 0.7.0 just made sure you can decrypt apps that have a minimum OS version higher than your current OS version

**Comment by binnichtaktiv** [comment]
> azule -i [bundle id of app you want to decrypt] -o [output directory]
> 
> Bundle id should look smth like 'com.google.ios.youtube' (the bundleid of youtube)
> 
> And no, you don't need to have the app installed

And do I have to type in my Apple ID and password?

**Comment by binnichtaktiv** [comment]
> > azule -i [bundle id of app you want to decrypt] -o [output directory]
> > Bundle id should look smth like 'com.google.ios.youtube' (the bundleid of youtube)
> > And no, you don't need to have the app installed
> 
> How do we decrypt apps for iOS 15 and 16 since there is no jailbreak available?

That’s why he made this😂 you can decrypt iOS 15 and 16 apps on a iOS 14 jailbroken device

**Comment by binnichtaktiv** [comment]
> azule -i [bundle id of app you want to decrypt] -o [output directory]
> 
> Bundle id should look smth like 'com.google.ios.youtube' (the bundleid of youtube)
> 
> And no, you don't need to have the app installed

Can I decrypt paid apps with it?

**Comment by Al4ise** [comment]
If you give azule an apple id that has the app purchased already, yeah, why not
