### ISSUE TITLE
[*] Invalid App - bad app source?

### ISSUE THREAD

**Issue by victokurk** [Al4ise/Azule#107]
Get an error when running command to inject tweak
[*] Invalid App
My app was downloaded on a jailbroken device using appstore++ with app thinning disabled. I exported the app using bfdecrypt. I was able to install the app and tweak using sideloadly successfully, but as I have a Pro AppDB account, I want to combine the two to not have to re-sign every week. 
Is my app source bad? what other methods do you use to download decrypted IPA files? I downloaded through iTunes store (12.6.3) on windows, but the app is encrypted, and I have no way to decrypt without a Mac computer, so I was unable to use that IPA file.

**Comment by Al4ise** [comment]
can you show me exactly what command you used?

**Comment by victokurk** [comment]
WSL azule -j -n Decryptedapp1 -i C:\WSL\decrypted-app-1.ipa -o C:\WSL\ipa -f C:\WSL\com.decryptedapp.tweak_3.19.1_iphoneos-arm.deb

**Comment by Al4ise** [comment]
wsl can't read windows directories. put the ipa in wsl somewhere and then run azule with the new directory

**Comment by victokurk** [comment]
Ok. I've moved to the Azule Directory and ran
WSL azule -j -n Decrypytedapp1 -i ~/Azule/decrypted-app-1.ipa -o ~/Azule/bin -f ~/Azule/com.decryptedapp.tweak_3.19.1_iphoneos-arm.deb
[*] Extracting iPA...
/usr/local/bin/azule: line 789: unzip: command not found
[*] Couldn't extract IPA

Line 789 states:
unzip -q "$ipadir" -d "$dir"

I know its not the original issue, but any help would be appreciated. Thanks.

**Comment by Al4ise** [comment]
there are installation instructions. please refer to them

**Comment by victokurk** [comment]
I figured the unzip problem out. had to run
sudo apt install zip unzip
however there is some toolchain error


[*] Extracting iPA...
[*] IPA extracted
/usr/local/bin/azule: line 865: /root/Azule/toolchain/bin/ldid: cannot execute binary file: Exec format error
/usr/local/bin/azule: line 866: /root/Azule/toolchain/bin/ldid: cannot execute binary file: Exec format error
otool: error while loading shared libraries: libc++abi.so.1: cannot open shared object file: No such file or directory
[*] Couldn't set app rpath

**Comment by Al4ise** [comment]
https://github.com/Al4ise/Azule/wiki

**Comment by victokurk** [comment]
I'm not sure why you're linking to the wiki. I've read all the instructions and followed them carefully. I'm using WSL with Ubuntu-2110. I'm getting an Exec format error, which from my research indicates that the program is not compatible with the operating system. I'm not sure where to go from here. Can you please assist? Thanks
