### ISSUE TITLE
Resigning Error in linux

### ISSUE THREAD

**Issue by mamareza0098** [Al4ise/Azule#109]
Hi,
Thank you for developing this tool. I am using Azule for injecting dylibs and resigning apps with tools like zsign with no problem at all in my mac, but when I want to use this procedure in our linux server Azule injects dylib properly but i can't resign it with zsign facing this error:

>>> Can't Get BundleID, BundleVersion, or BundleExecute in Info.plist! /tmp/zsign_folder_1657474762689301/Payload/Calm.app
>>> Signed Failed! (0.001s, 574us)

 Resigns with no injection works fine in linux too. May i know the issue is with Azule or not? 
pardon my bad english :)

**Comment by Al4ise** [comment]
i honestly have no clue. hope you had your problem fixed

**Comment by mamareza0098** [comment]
Hi
The problem is solved, i was running azule as root.
Thanks

Regards,
Mohamad reza Ahvaraki
iOS developer & M.Sc Encryption and secure Communication engineer
