### ISSUE TITLE
Banned .dylib or something? 

### ISSUE THREAD

**Issue by iammanpreetsingh** [Al4ise/Azule#112]
I am injecting YoutubeMusic with YTMusicUltimate...

but somehow azule is not injecting if the .dylib name is "YTMusicUltimate v1.1.8.dylib"

If I change the name to something else, it successfully injects. 

How's that's possible ??

Check image here
https://ibb.co/ch8Jv8j

**Comment by Al4ise** [comment]
could you send me the deb?

**Comment by iammanpreetsingh** [comment]
[https://we.tl/t-LwPUsLuq3Z](url)

**Comment by Al4ise** [comment]
link doesnt really work

**Comment by Al4ise** [comment]
Though my guess is that the .plist of the .dylib doesn't specify yt music as a target >> azule ignores it. When you change the name of the dylib, the plist no longer corresponds to it, so azule just injects it without checking

**Comment by Al4ise** [comment]
> Though my guess is that the .plist of the .dylib doesn't specify yt music as a target >> azule ignores it. When you change the name of the dylib, the plist no longer corresponds to it, so azule just injects it without checking

nvm

**Comment by Al4ise** [comment]
please reopen if you're still having this issue
