### ISSUE TITLE
Libhooker no longer available 

### ISSUE THREAD

**Issue by EduAlexxis** [Al4ise/Azule#114]
Refer to this image: https://imgur.com/a/czTj3rl

How can I skip the check of libhooker on the server? Let's say I somehow get the libhooker.deb how do I import it to azule manually, so it doesn't try to download it from the servers?

**Comment by Al4ise** [comment]
i can't really reproduce this, everything downloads fine on my end. Could you try running 'azule -R' and seeing if that works?

**Comment by EduAlexxis** [comment]
The same result, I tried on my iPhone and my Linux desktop

**Comment by EduAlexxis** [comment]
> i can't really reproduce this, everything downloads fine on my end. Could you try running 'azule -R' and seeing if that works?


The same result, I tried on my iPhone and my Linux desktop

**Comment by Al4ise** [comment]
I'll look into it, though i have no idea really what's going on

**Comment by Al4ise** [comment]
should be fixed in the latest update

**Comment by turannul** [comment]
> should be fixed in the latest update

![Uploading 82E2F720-99DC-4C22-90AD-753141E4DE5F.png…]()

Having same issue v0.7.4

**Comment by turannul** [comment]
> should be fixed in the latest update

Having same issue v0.7.4
![F670CBD2-DCA3-49DD-AA8E-206E3B520B49](https://user-images.githubusercontent.com/84424530/191265550-1645c5b7-c2bf-4021-a046-afa319022597.png)

**Comment by HearseDev** [comment]
> libhooker's gone now, you should be good on 0.7.5
Even though one can inject libhooker manually. I think this would an amazing opportunity to only display libhooker with the unsupported options only. Especially for people that use libhooker for certain reasons

**Comment by Al4ise** [comment]
the implementation of libhooker literally didn't work either ways, i kept it in hopes that coolstar would update it for jailed use. They did not
