### ISSUE TITLE
New update compression "doesn't work"

### ISSUE THREAD

**Issue by k3v1nwrld** [Al4ise/Azule#115]
Basically was making a yt ipa with the tweaks i usually inject and noticed that the file size was way bigger than it normally is.Before the latest update, yt was around 93MB (after injecting tweaks, removing watch app etc) and now its around 220MB.I checked to see if maybe the yt update was the problem but its not.Imo this is a big problem for people who sideload from their phone (AltStore/TrollStore) bc the ipa takes much longer to be sent

**Comment by Al4ise** [comment]
i mean if you give it a 200mb file initially, its going to output a 200mb file. the new update basically doesn't unzip 98% of the file you give it, it just works with what you give it

**Comment by k3v1nwrld** [comment]
Could there be a way to go back to the old version??Or maybe to make it an option to choose which one you want?

**Comment by Al4ise** [comment]
I'll add a switch to use better compression later, though its going to be insanely inefficient and i'll likely put a 'please dont use' notice next to it. I'd really recommend you just find an ipa with better compression for now

**Comment by k3v1nwrld** [comment]
Thank you!

**Comment by Al4ise** [comment]
in the new update, you can use -z to have azule shrink ipa files again
