### ISSUE TITLE
Couldn't set app rpath ??

### ISSUE THREAD

**Issue by heinekenpsx** [Al4ise/Azule#117]
Try with Kodi app repackaged as ipa from the deb file
xXx:~/Downloads root# azule -i K.ipa -b ko.di -o ~ -j
[*] Couldn't set app rpath

**Comment by Al4ise** [comment]
fixed in the latest update

**Comment by heinekenpsx** [comment]
New issue ?
Nó xảy ra với lệnh -b, invalid app

xXx:~ root# cd Downloads/
xXx:~/Downloads root# azule -i MemScanTS+H5GGv7.
9.deb.ipa -b a.b -o . -j
[*] Checking for App Updates...
[*] Invalid App
xXx:~/Downloads root# azule -i iSTB\ \(v1.24.0\ 
v102\ Univ\ FW\ 64bit\ os110\ ok14\)-user_hidden
.bfi2.ipa -b s.t.b -o . -j
[*] Checking for App Updates...
parse error: Invalid numeric literal at line 1, column 24
[*] Invalid App
xXx:~/Downloads root# azule -i VPN\ Prime_2.2.0\
[tg\@iapps_ipa\].ipa -b a.b -o . -j
[*] Checking for App Updates...
[*] Invalid App
xXx:~/Downloads root# azule -i kodi.ipa -b ko.di
 -o . -j
[*] Checking for App Updates...
[*] Invalid App

**Comment by Al4ise** [comment]
Expect an update on that in like 1-2 days

**Comment by Al4ise** [comment]
May be good now?

**Comment by Al4ise** [comment]
please reopen if you are still having this issue
