### ISSUE TITLE
Unable to remove watch app (zip error)

### ISSUE THREAD

**Issue by teelekkung** [Al4ise/Azule#118]
Here log with on option to keep watch app
sahakiyat@Sahakiyats-MacBook-Air ~/Downloads % azule -i Spotify.ipa -o ./ -f ../Desktop/Spotify/Spotilife.dylib -n Spotifff -H -u -e -v
[*] Checking for Updates...
[*] Azule is Up to Date
[*] Temporary Directory has been created
[*] App executable is @executable_path/Spotify
[*] Stripped codesign from app executable
[*] App rpath is @executable_path/Frameworks
[*] Spotilife.dylib will be imported
[*] Copied Spotilife.dylib to work directory
[*] Copied Spotilife.dylib to app directory
[*] Codesign stripped from Spotilife.dylib
[*] ID Successful
[*] Injected Spotilife.dylib
[*] Removed UISupportedDevices from app
[*] Restored App Entitlements
[*] Generating iPA...

zip error: Nothing to do! (/Users/sahakiyat/Downloads/Spotifff.ipa)

zip error: Nothing to do! (/Users/sahakiyat/Downloads/Spotifff.ipa)

zip error: Nothing to do! (/Users/sahakiyat/Downloads/Spotifff.ipa)
[*] Couldn't Remove Watch App
[*] Removed Extensions
[*] Generated IPA at /Users/sahakiyat/Downloads/Spotifff.ipa

and with option to keep watch app

sahakiyat@Sahakiyats-MacBook-Air ~/Downloads % azule -i Spotify.ipa -o ./ -f ../Desktop/Spotify/Spotilife.dylib -n Spotifff -H -u -e -v -y
[*] Checking for Updates...
[*] Azule is Up to Date
[*] Temporary Directory has been created
[*] App executable is @executable_path/Spotify
[*] Stripped codesign from app executable
[*] App rpath is @executable_path/Frameworks
[*] Spotilife.dylib will be imported
[*] Copied Spotilife.dylib to work directory
[*] Copied Spotilife.dylib to app directory
[*] Codesign stripped from Spotilife.dylib
[*] ID Successful
[*] Injected Spotilife.dylib
[*] Removed UISupportedDevices from app
[*] Restored App Entitlements
[*] Generating iPA...
[*] Removed Extensions
[*] Generated IPA at /Users/sahakiyat/Downloads/Spotifff.ipa

**Comment by Al4ise** [comment]
should be fixed now

**Comment by Al4ise** [comment]
please reopen if you're still having this issue
