### ISSUE TITLE
.appex files are copied to the wrong folder

### ISSUE THREAD

**Issue by binnichtaktiv** [Al4ise/Azule#119]
Hi
can you please fix this? .appex files should be copied to the Plugins folder but right now they are in the .app folder. So they are useless if they are in the .app folder, they need to be in the Plugins folder. It would be great if you can fix this because I dont have to unzip copy the .appex and zip the ipa again then 😁🫶🏻
![2022-09-20 19 16 21](https://user-images.githubusercontent.com/96953964/191322681-1fc686dc-9765-44db-9f24-f207e4385122.jpg)
![2022-09-20 19 16 30](https://user-images.githubusercontent.com/96953964/191322703-8a3e34a3-7af1-416f-b058-c445bbd34f2d.jpg)

**Comment by Al4ise** [comment]
I'll do that in the next update

**Comment by Al4ise** [comment]
update's out, should work there

**Comment by binnichtaktiv** [comment]
> update's out, should work there

thank you everything is working again❤️❤️❤️
