### ISSUE TITLE
Couldn't set app executable

### ISSUE THREAD

**Issue by cakarlen** [Al4ise/Azule#120]
Hi, I'm getting the following error:

<img width="429" alt="CleanShot 2022-10-04 at 13 41 48@2x" src="https://user-images.githubusercontent.com/33635487/193889078-71820df6-aa80-4e87-a481-dbcc05744540.png">

Here is my full command I am running: 
`azule -i /Users/test/Development/iOS/Jailbreak/Instagram.ipa -v -f /Users/test/Development/iOS/Jailbreak/me.alfhaily.rocket_3.8.0_iphoneos-arm.deb /Users/test/Development/iOS/Jailbreak/rocketbootstrap_1.1.0_libhooker2-iphoneos-arm.deb -o /Users/test/Development/iOS/Jailbreak/InstagramTweak.ipa`

I am running MacOS 12.3, M1 chip, installed using instructions in wiki. Instagram is decrypted using standard methods and is the latest version.

**Comment by heinekenpsx** [comment]
-o <directory> (not file)

**Comment by cakarlen** [comment]
Still having the same issue

**Comment by cakarlen** [comment]
Awesome, please let me know when a fix has been pushed for testing

**Comment by Al4ise** [comment]
update's out, lmk if it fixes it for you

**Comment by cakarlen** [comment]
Fixed. Thanks for the update
