### ISSUE TITLE
ssl cert error when downloading libhooker 

### ISSUE THREAD

**Issue by binnichtaktiv** [Al4ise/Azule#122]
Hi it’s me again🥲

I had to restore rootfs and rejb because I had a problem and now I get this idk why I even tried to downgrade azule. Before rootfs restore everything worked perfectly😍
![B95D548E-96D5-44B9-8BE8-75EF1EE59EE6](https://user-images.githubusercontent.com/96953964/194858057-4758a257-91d1-44c4-8d8e-15a2cd8f8b7b.png)
![992CC026-A61B-4FA5-B8F9-D79B06CDC736](https://user-images.githubusercontent.com/96953964/194858068-3bd146b4-aab4-466f-9897-8891c644fa19.png)

**Comment by Al4ise** [comment]
I'll just remove libhooker in the next update, though release may take some time as im doing smth big rn

**Comment by binnichtaktiv** [comment]
> I am him?

Bruh I only looked at the name in the email and not here on GitHub mb😅 can I ask what you are working on?😄

**Comment by Al4ise** [comment]
A kind of code refactor that has 2 key parts of azule in different executables. It will allow users to just install and use what they need, instead of the entire bloated thing, and it will allow me to not want to kms whenever i open the project to make any changes whatsoever

**Comment by binnichtaktiv** [comment]
> A kind of code refactor that has 2 key parts of azule in different executables. It will allow users to just install and use what they need, instead of the entire bloated thing, and it will allow me to not want to kms whenever i open the project to make any changes whatsoever

sounds pretty good.  how far are you?  so if I understood correctly, it is azule 2.0 but divided into several parts?  Sorry for the questions I'm just interested 😀

**Comment by Al4ise** [comment]
idk i'll need like a day more max. Azule 2.0 i wouldnt call it as i'm not even comfortable saying its ready for a 1.0 bit it's going to be a good azule 0.7.5

**Comment by binnichtaktiv** [comment]
> idk i'll need like a day more max. Azule 2.0 i wouldnt call it as i'm not even comfortable saying its ready for a 1.0 bit it's going to be a good azule 0.7.5

okay then I wish you much success and thank you for doing this for us ❤️🫶🏻

**Comment by Al4ise** [comment]
yeah don't thank me, i just want to release something stable before i let the project die

**Comment by Al4ise** [comment]
I will most likely just.. uhm.. hopefully not too many are needed

**Comment by binnichtaktiv** [comment]
> I will most likely just.. uhm.. hopefully not too many are needed

I wish I could help but I'm just learning to code and the best I can do is scanf😭😂

**Comment by Al4ise** [comment]
Either ways you shouldnt be learning bash

**Comment by binnichtaktiv** [comment]
> Either ways you shouldnt be learning bash

Why?🤔

**Comment by Al4ise** [comment]
It's barely a language, its way too slow.. it's like a shitty version of python

**Comment by binnichtaktiv** [comment]
> It's barely a language, its way too slow.. it's like a shitty version of python

and why did you write that in bash?  is there no other way or why?  could azule also be written in python?

**Comment by Al4ise** [comment]
idk, i felt like it and i was deep into shell scripting when I started writing this. Also, update's out, libhooker's gone

**Comment by binnichtaktiv** [comment]
> idk, i felt like it and i was deep into shell scripting when I started writing this. Also, update's out, libhooker's gone

but could I "rewrite" azule if i knew how to code in python?
