### ISSUE TITLE
line 497: ar: command not found.

### ISSUE THREAD

**Issue by yoji29** [Al4ise/Azule#124]
im trying to inject deb and this happened.. im using wsl ubuntu 20.4
![azulewsl](https://user-images.githubusercontent.com/115745515/195717017-c4a7dc6a-2e50-4c04-965c-7ca19ab74b2d.jpg)

**Comment by Al4ise** [comment]
can you just run azule -R

**Comment by yoji29** [comment]
this fix the problem thank you :D
