### ISSUE TITLE
Installed app crashed immediately

### ISSUE THREAD

**Issue by CySxL** [Al4ise/Azule#128]
Azule version : 0.7.6
Device : iPhone X
iOS : 14.3
Jailbreak : Taurine 1.1.6

So with the latest build of Azule, the app got installed on home screen as well instead of just grabbing the IPA. Which is very nice for me but the app installed just crashed immediately.

for more details, I want to install Uber eats app (requires at least iOS 14.8) on my iOS 14.3 device. 

This is the command I used : 
azule -i com.ubercab.UberEats -o /var/mobile/Documents -r

After processing the Uber eats app is installed on home screen automatically but crashes immediately. Also I found it has the latest version which apparently not works for iOS 14.3.

Update : Tried -c as well. Still crashes on home screen immediately. And the version number doesn't change at all, still showing the latest (6.133.10001) instead of what I set for in Azule (6.108.10000)

**Comment by CySxL** [comment]
So my requests and are : 

1. Two separate new commands for users to choose just directly grabbing the IPA and save in Filza directory or directly installing app on homescreen

2. A new command to bypass Minimum OS Version as ease. But I don't know if it's doable.

**Comment by binnichtaktiv** [comment]
not azules fault.

**Comment by CySxL** [comment]
> not azules fault. 

Any further proof ? This simple sentence won't help with any issue I have

**Comment by binnichtaktiv** [comment]
> > not azules fault.
> 
> Any further proof ? This simple sentence won't help with any issue I have

Use choicy and disable tweaks for your app. And the proof is that it’s working for everyone

**Comment by CySxL** [comment]
> > > not azules fault.
> 
> > 
> 
> > Any further proof ? This simple sentence won't help with any issue I have
> 
> 
> 
> Use choicy and disable tweaks for your app. And the proof is that it’s working for everyone else

It's not working for my friends too. How is that "working for everyone" ?

**Comment by CySxL** [comment]
> > > not azules fault.
> 
> > 
> 
> > Any further proof ? This simple sentence won't help with any issue I have
> 
> 
> 
> Use choicy and disable tweaks for your app. And the proof is that it’s working for everyone else

 ![image](https://user-images.githubusercontent.com/15531137/196352218-ae1f18a3-dfa9-452a-8013-3a22fd978bfd.png)
https://user-images.githubusercontent.com/15531137/196352235-5b30057d-964f-468e-9bcf-4a2395ee0d17.MOV


How is this "working for everyone" ?

**Comment by binnichtaktiv** [comment]
> > > > not azules fault.
> > 
> > 
> > > 
> > 
> > 
> > > Any further proof ? This simple sentence won't help with any issue I have
> > 
> > 
> > Use choicy and disable tweaks for your app. And the proof is that it’s working for everyone else
> 
> ![image](https://user-images.githubusercontent.com/15531137/196352218-ae1f18a3-dfa9-452a-8013-3a22fd978bfd.png) https://user-images.githubusercontent.com/15531137/196352235-5b30057d-964f-468e-9bcf-4a2395ee0d17.MOV
> 
> How is this "working for everyone" ?

this you?🤓
Btw check if the ipa is decrypted properly and check if the tweak is compatible with the ipa version

**Comment by CySxL** [comment]
Not really helpful but thank you. I'll wait for a true dev to work together.

**Comment by Al4ise** [comment]
I'd rather not touch this conversation. Does azule work when you remove the -r arguement?

**Comment by CySxL** [comment]
> I'd rather not touch this conversation. Does azule work when you remove the -r arguement?

Sadly no. Is it normal that Azule automatically install IPA at the same time ?

![image](https://user-images.githubusercontent.com/15531137/196590698-fc047c41-ddd9-4eeb-978b-385e85ae304e.png)
https://user-images.githubusercontent.com/15531137/196590718-43dcb722-649d-40c5-a2f4-1c86397a2a16.MOV

**Comment by Al4ise** [comment]
can you sideload the clean ipa, that hasnt been processed with azule?

**Comment by CySxL** [comment]
> can you sideload the clean ipa, that hasnt been processed with azule?

Sure. What way you want me to try ? Like sideload with Altstore or Trollstore ? And can I use other tweaks like bfdecrypt to get the IPA ?

**Comment by Al4ise** [comment]
Sideload like you would have sideloaded the tweaked ipa, idc, not with trollstore ig?

**Comment by Al4ise** [comment]
And you could probably just use azule to get the ipa, thats azule -i [bundleid of app] -o [outdir]. But bfdecrypt works too

**Comment by CySxL** [comment]
> And you could probably just use azule to get the ipa, thats azule -i [bundleid of app] -o [outdir]. But bfdecrypt works too

yeah I know that. Can we get the ipa with specific version ?

Btw the ipa file Azule created is successfully sideloaded with Trollstore. But the app on homescreen installed by Azule crashes immediately at launch

**Comment by Al4ise** [comment]
oh yeah that's because azule temporarily bypasses the minimum ios version for the sake of the app devrypting properly. it's how it should be

**Comment by CySxL** [comment]
> oh yeah that's because azule temporarily bypasses the minimum ios version for the sake of the app devrypting properly. it's how it should be

Sorry not quite understand haha, so the app installed by Azule on HS is normal to crash at launch right ?

**Comment by Al4ise** [comment]
That's correct

**Comment by CySxL** [comment]
> That's correct

Ok got it. So for my understanding the app on HS is technically an useless app, the truly working thing is the IPA created by Azule in output path right ?

**Comment by Al4ise** [comment]
Most times yeah, though if you install the azule-generated ipa on an ios version lower than the required ios version, it will still crash

**Comment by CySxL** [comment]
> Most times yeah, though if you install the azule-generated ipa on an ios version lower than the required ios version, it will still crash

Thanks for the help ! Now I finally understand all things 😂 

Btw will Azule have an ability to decrypt the current build of an already installed app instead of downloading the latest build from AppStore ?

**Comment by Al4ise** [comment]
There is an option to ignore updates already. Not sure what it was though, look in the -h menu

**Comment by CySxL** [comment]
> There is an option to ignore updates already. Not sure what it was though, look in the -h menu

Ah cool !! Do you mean the -I command ?

**Comment by CySxL** [comment]
> There is an option to ignore updates already. Not sure what it was though, look in the -h menu

Just tested with the -l command.
Yeah it decrypted the currently installed App (Discord) but eventually fail for decrying 3 files w/o injecting tweak.

![image](https://user-images.githubusercontent.com/15531137/196613834-592191bb-818f-4347-92d0-ea3d665276dd.jpeg)

**Comment by Al4ise** [comment]
i mean there is a reason the default is to update the app. for some apps azule's decryption method simply fails, idk why

**Comment by CySxL** [comment]
> Almost never fails when you get an ipa from ipatool first though

Is the command of ipatool contained in azule too ?

**Comment by Al4ise** [comment]
yeah
