### ISSUE TITLE
Error with sudo command 

### ISSUE THREAD

**Issue by Cap-OA** [Al4ise/Azule#133]
![image](https://user-images.githubusercontent.com/92122188/209982162-54a811a8-e1de-4175-867b-5bfcbaa6a6c3.png)

not finding the azule directory in usr/local/bin. Manually looked and it doesn't exist.

**Comment by Al4ise** [comment]
uhhhh can you try writing the full directory instead of the thing with the ~

**Comment by Al4ise** [comment]
please reopen if you're still having this issue
