### ISSUE TITLE
Latest update breaks injecting multiple debs/dylibs

### ISSUE THREAD

**Issue by k3v1nwrld** [Al4ise/Azule#135]
Title explains it pretty much. I've tried it on Ubuntu and Mac and both of them stop responding when I press enter. Thanks!

**Comment by giangcoi89** [comment]
same issues on Linux/WLS

**Comment by Al4ise** [comment]
should be fixed now, sorry

**Comment by CySxL** [comment]
Same on iOS 14.8. I can only inject the most 3 .debs. More then 4 .debs would lead to repo refreshing error.
