### ISSUE TITLE
Cannot set environment variable

### ISSUE THREAD

**Issue by ExeRhythm** [Al4ise/Azule#26]
Hi, I have a problem with the installation. How do I set environment variable $AZULE? If I run:
`echo "export AZULE=~/azule" >> ~/.zprofile`
then nothing happens, the variable is not set, because if I run `ls $AZULE` I get `ls` of my home directory (I am on Mac). How do I fix this? Thanks!

**Comment by Al4ise** [comment]
Initially $AZULE will be empty. After cloning the github repository(in the next step), the folder will show up in your home directory. Let me know if that answers your question

**Comment by ExeRhythm** [comment]
I did clone the repo. Here's the log:
```
exerhythm@Matthews-iMac ~ % git clone --recursive https://github.com/Al4ise/Azule $AZULE
Cloning into 'Azule'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 486 (delta 52), reused 0 (delta 0), pack-reused 380
Receiving objects: 100% (486/486), 232.40 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (274/274), done.
exerhythm@Matthews-iMac ~ % echo "export AZULE=~/azule" >> ~/.zprofile
exerhythm@Matthews-iMac ~ % chmod +x $AZULE/Install
chmod: /Install: No such file or directory
exerhythm@Matthews-iMac ~ %
```

**Comment by ExeRhythm** [comment]
Relaunching terminal fixed the problem. Thanks!
