### ISSUE TITLE
Error: /usr/local/bin/azule:223: no matches found

### ISSUE THREAD

**Issue by Letscoder** [Al4ise/Azule#28]
I followed instructions but on the last stage with 'Choose Dylib' this problem occurs for every dylib.
`/usr/local/bin/azule:223: no matches found: Payload/*.app/Frameworks/CydiaSubstrate.framework/CydiaSubstrate`

My .ipa-s are certainly decrypted. Console option with enlisting dylibs with `-d` also fails.It doesn't depend on tweak.

My working machine is Mac with M1 processor

**Comment by NickoTheDev** [comment]
Do you have Xcode and Xcode CLI Utils installed? You can check by running `xcode-select --version` in a Terminal window.

**Comment by Letscoder** [comment]
I found that this error occurs when the target .ipa does not contains 'Frameworks' folder, though manual creation through converting .ipa to .zip and archiving back doesn't work.

**Comment by Al4ise** [comment]
Do you still have this problem?

**Comment by elzari** [comment]
With Azule 0.7-2 impossible to load CEPHEI to IPA.
 
Extracting /home/fede/ws.hbang.common_1.14_iphoneos-arm.deb...
ws.hbang.common_1.14_iphoneos-arm.deb extracted
Copied libhbangcommon.dylib to app directory
Injected libhbangcommon.dylib
Copied libcepheiprefs.dylib to app directory
Injected libcepheiprefs.dylib
Copied libcephei.dylib to app directory
Injected libcephei.dylib
Copied libhbangprefs.dylib to app directory
Injected libhbangprefs.dylib
Copied libhbangprefs.bundle to app directory
Copied Cephei.bundle to app directory
Copied CydiaSubstrate.framework to app directory
Copied Cephei.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/Library/Frameworks/Cephei.framework/Info.plist
Copied CepheiUI.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/Library/Frameworks/CepheiUI.framework/Info.plist
Copied CepheiPrefs.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/Library/Frameworks/CepheiPrefs.framework/Info.plist
Copied Cephei.framework to app directory
Copied CepheiUI.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/usr/lib/CepheiUI.framework/Info.plist
Copied CepheiPrefs.framework to app directory
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libhbangcommon.dylib (No such file or directory)
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libcepheiprefs.dylib (No such file or directory)
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libcephei.dylib (No such file or directory)
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libhbangprefs.dylib (No such file or directory)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/Cephei.framework/ (No such device)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/CepheiUI.framework/ (No such device)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/CepheiPrefs.framework/ (No such device)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/CepheiUI.framework/ (No such device)
ID Successful
Re-Link Successful
Generating iPA...
Generated IPA at /home/fede/test//tunepro.ipa+ws.hbang.common_1.14_iphoneos-arm.deb.ipa

Please, any idea? Ipa not working....

THanks

**Comment by nicknitewolf** [comment]
Please re-open if you still have the issue. Thanks!
