### ISSUE TITLE
"_____ isn't available on Parcility. Try getting the files manually." Despite all files being provided manually

### ISSUE THREAD

**Issue by BitGrub** [Al4ise/Azule#31]
No matter what I do, Azule insists that the local .deb files I provide "aren't available on Parcility". Am I wrong in thinking I have to provide the full filepath to the tweak packages, separated by spaces?

Also "/usr/local/bin/azule:169: no such file or directory: \~/Azule/bin/jq
(23) Failed writing body"  **even though \~/Azule/bin/jq IS a file**

**Comment by Al4ise** [comment]
Hey, could you try using the build on the Verbose branch and see if it works?

**Comment by Al4ise** [comment]
Can you try the newest build?

**Comment by BitGrub** [comment]
Seems to be working now, thanks!

**Comment by bakedpotato191** [comment]
I'm experiencing this on the newest build. It happens when the tweak directory contains spaces in it's name.
