### ISSUE TITLE
Output directory is broken when using existing directory

### ISSUE THREAD

**Issue by nicknitewolf** [Al4ise/Azule#32]
Verbose output using `-o ~/outdir/`

```
Output Name is ABCD
Output Directory is /Users/nick///
Work directories has been created
```

**Comment by Al4ise** [comment]
I'm having difficulties recreating your issue, can you elaborate on what exactly you are doing, and what exactly the issue is?

**Comment by nicknitewolf** [comment]
> I'm having difficulties recreating your issue, can you elaborate on what exactly you are doing, and what exactly the issue is?

I have a folder that is already created called ~/outdir
When I set the output folder as ~/outdir, azule seems to set the output directory with as ~// instead of the actual directory

**Comment by Al4ise** [comment]
could you try the build on the experimental branch?

**Comment by nicknitewolf** [comment]
Still doesn't work. This happens:

```azule -n BetterCercube -i ~/BetterCercube/YouTube.ipa -o ~/BetterCercube -f ~/BetterCercube/me.alfhaily.cercube_5.2.26.deb -d Cercube.dylib -v
Path to IPA is /Users/nick/BetterCercube/YouTube.ipa
Output Name is BetterCercube
/Users/nick/BetterCercube/BetterCercube
Output Directory is /Users/nick//
Work directories have been created```

**Comment by Al4ise** [comment]
the thing i just pushed to experimental should work now

**Comment by nicknitewolf** [comment]
Works, thanks!
