### ISSUE TITLE
Failed to fetch toolchain

### ISSUE THREAD

**Issue by LaxusiC** [Al4ise/Azule#35]
root@DESKTOP-N3QRQ4A:~# chmod +x $AZULE/Install
root@DESKTOP-N3QRQ4A:~# $AZULE/Install
Fetching toolchain...
tar: unrecognized option '--zst'
Try 'tar --help' or 'tar --usage' for more information.
rsync: change_dir "/tmp/tmp.jsF06pppLw/swift-5.3.2-RELEASE-ubuntu18.04" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]

OS: Ubuntu 18.04 WSL1

**Comment by Al4ise** [comment]
Make sure you have zstd installed

**Comment by LaxusiC** [comment]
> Make sure you have zstd installed

root@DESKTOP-N3QRQ4A:~# sudo apt install zstd
Reading package lists... Done
Building dependency tree
Reading state information... Done
zstd is already the newest version (1.3.3+dfsg-2ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 206 not upgraded.

Yes it already installed, I follow the instruction on the Wiki page

**Comment by Al4ise** [comment]
uhm.. apt dist-upgrade?

**Comment by LaxusiC** [comment]
> uhm.. apt dist-upgrade?

Updated all, still getting the previous issue :/

**Comment by LaxusiC** [comment]
Ok I fixed it, the tar command is wrong in Install file

Change to `tar -I zstd -xvf swift-5.3.2-RELEASE-ubuntu18.04.tar.zst -C $TMP` in line #27 fixed it :)

**Comment by LaxusiC** [comment]
Getting new issue lol
root@DESKTOP-N3QRQ4A:~# azule -m
Path to IPA: /root/Facebook.ipa
Files or Tweak IDs: com.facebook.Facebook
Output Directory: /root/AzuleFB.ipa
error: unknown format CFBundleExecutable

usage: plutil -<command> [options] <files>

commands:
  -lint (default)
  -help (this message)
  -p
  -convert <format>
  -insert <key> <value>
  -replace <key> <value>
  -remove <key>
  -extract <key> <format>

values:
  -bool <YES|NO>
  -integer <number>
  -float <number>
  -string <utf8>
  -data <base64>
  -date <iso8601>
  -xml <plist>
  -json <json>

formats:
  xml1
  binary1
  openstep1
  json
com.facebook.Facebook isn't available on Parcility. Try getting the files manually.
root@DESKTOP-N3QRQ4A:~#

**Comment by Al4ise** [comment]
Can you run it with the -v arguement?

**Comment by LaxusiC** [comment]
https://paste.bingner.com/paste/ovyt4

**Comment by Al4ise** [comment]
should work now
