### ISSUE TITLE
dylibs failing to inject

### ISSUE THREAD

**Issue by mattp12** [Al4ise/Azule#36]
I am trying to inject dylibs into YouTube that I decrypted using bfdecrypt. However, the resulting ipa that I load onto my device with AltStore acts just like the stock app, with nothing injected.

Here is the entire output when running `$AZULE/azule -v` and supplying the necessary arguments: [https://pastebin.com/jESKehbh](https://pastebin.com/jESKehbh) 

I noticed that on line 10 the output says unknown format CFBundleExecutable and on line 398 it says that the dylib failed to inject. Not sure if the first error is relevant, but the second one certainly looks important.

I also found it strange that the output gave the plutil usage, but that may be unrelated.

Do you have any idea why this would be happening?

**Comment by Al4ise** [comment]
can you try the latest version?

**Comment by mattp12** [comment]
I just tried using the latest version and all is working correctly, thanks for the update!
