### ISSUE TITLE
Sideloading on ios12 seems to be broken

### ISSUE THREAD

**Issue by nicknitewolf** [Al4ise/Azule#37]
A tester submitted this to me https://pastebin.com/GamHsEU2

**Comment by Al4ise** [comment]
Are you sure YouTube supports iOS 12?

**Comment by nicknitewolf** [comment]
> Are you sure YouTube supports iOS 12?

It seems to support it up to ios 11 sdk

**Comment by Al4ise** [comment]
hm yeah i just checked, youtube is ios 13+ and i can't even get it to install on an ios 12 device

**Comment by Al4ise** [comment]
Does sideloading the raw ipa without the tweaks imported work?

**Comment by nicknitewolf** [comment]
> Does sideloading the raw ipa without the tweaks imported work?

as of now I don't know. I do not have an ios 12 device
