### ISSUE TITLE
Getting some kind of errors

### ISSUE THREAD

**Issue by gotzlotz** [Al4ise/Azule#38]
I am getting this in the  Terminal Window…

sed: 1: "s/\(.*\)YouTube": unterminated substitute pattern
mkdir: : No such file or directory
caution: filename not matched:  _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb
rsync: link_stat "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Payload/*.app/Info.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7f8eb2706e80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7f8d3ec0bbb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7f89e9d06fd0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/_Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Tweak/Library/MobileSubstrate/DynamicLibraries/Cercube.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7fdc8f6075a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/_Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Tweak/Library/MobileSubstrate/DynamicLibraries/Cercube.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7faf34d07080 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7f9a86607140 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7f81d840b7f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/_Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Tweak/Library/MobileSubstrate/DynamicLibraries/zCercubeBoard.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7fc9b46071d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: link_stat "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/_Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Tweak/Library/MobileSubstrate/DynamicLibraries/zCercubeBoard.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Plists/plist.tmp: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “plist.tmp” couldn’t be opened because there is no such file." UserInfo={NSFilePath=Plists/plist.tmp, NSUnderlyingError=0x7f905f007140 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
cat: Plists/plist.tmp: No such file or directory
rm: Plists/plist.tmp: No such file or directory
rsync: mkdir "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Payload/*.app" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(545) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]
rsync: mkdir "/Users/marcus/Azule/.tmp/YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb/Payload/*.app/Frameworks" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(545) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]
ldid.cpp(3164): _assert(): errno=2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: Payload/*.app/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (No such file or directory)

zip error: Nothing to do! (try: zip -rqX YouTube _Watch,_Listen,_Stream_v.16.18.5.ipa+me.alfhaily.cercube_5.2.27_iphoneos-arm.deb.ipa . -i Payload)

**Comment by Al4ise** [comment]
To switch branches you should first run 'rm -rf $AZULE', and then run these commands

git clone --recursive https://github.com/Al4ise/Azule $AZULE -b Experimental

chmod +x $AZULE/Install

$AZULE/Install

Note though that the experimental branch rarely works to its full extent. Thats the main reason I don't include instructions for switching to it in the wiki

**Comment by gotzlotz** [comment]
Got it…thanks

**Comment by gotzlotz** [comment]
Updated 1st post

**Comment by Al4ise** [comment]
Can you try the latest build on the main branch?

**Comment by nicknitewolf** [comment]
Please reopen if you still have the issue. Thanks!
