### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by Am1nCmd** [Al4ise/Azule#40]
Hi, I have error when trying to install Azule

```
Amins-MacBook-Pro:~ Am1nCmd$ chmod +x $AZULE/Install
chmod: /Install: No such file or directory
```

it say no such file or directory

I have been check on ~/.profile its already available

```
export AZULE=~/Azule
==> Searching for similarly named formulae...
This similarly named formula was found:
giter8
To install it, run:
  brew install giter8
==> Searching for a previously deleted formula (in the last month)...
```

also Azule directory is available

I'm trying to using chmod -R 777 but the result still same 
`chmod: /Install: No such file or directory`

I'm using macOS Mojave anyway

**Comment by Al4ise** [comment]
You need to restart your terminal after setting the env variable. If you did that already but it still doesnt work, try exporting to ~/.zprofile, restarting the terminal, and trying again

**Comment by nicknitewolf** [comment]
Hi please try again with the new install instructions

**Comment by Am1nCmd** [comment]
Sure

Sent from my iPhone

On 6 Aug 2021, at 7.58 PM, Nicholas Lim ***@***.***> wrote:

﻿

Hi please try again with the new install instructions

**Comment by Am1nCmd** [comment]
it still say 
![image](https://user-images.githubusercontent.com/15339573/128609699-655c1882-1a11-4f75-b9e1-b645a20ff624.png)


I already restart the Terminal btw

**Comment by nicknitewolf** [comment]
show me your `cat ~/.profile`

**Comment by nicknitewolf** [comment]
Please re-open this issue if you still have a problem
