### ISSUE TITLE
ERROR TO LOAD CEPHEI FRAMEWORK

### ISSUE THREAD

**Issue by elzari** [Al4ise/Azule#41]
With Azule 0.0.7-2 impossible to load CEPHEI to IPA.

Extracting /home/fede/ws.hbang.common_1.14_iphoneos-arm.deb...
ws.hbang.common_1.14_iphoneos-arm.deb extracted
Copied libhbangcommon.dylib to app directory
Injected libhbangcommon.dylib
Copied libcepheiprefs.dylib to app directory
Injected libcepheiprefs.dylib
Copied libcephei.dylib to app directory
Injected libcephei.dylib
Copied libhbangprefs.dylib to app directory
Injected libhbangprefs.dylib
Copied libhbangprefs.bundle to app directory
Copied Cephei.bundle to app directory
Copied CydiaSubstrate.framework to app directory
Copied Cephei.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/Library/Frameworks/Cephei.framework/Info.plist
Copied CepheiUI.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/Library/Frameworks/CepheiUI.framework/Info.plist
Copied CepheiPrefs.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/Library/Frameworks/CepheiPrefs.framework/Info.plist
Copied Cephei.framework to app directory
Copied CepheiUI.framework to app directory
error: unable to read /tmp/tmp.io8aimCq1T/8200/Tweak/usr/lib/CepheiUI.framework/Info.plist
Copied CepheiPrefs.framework to app directory
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libhbangcommon.dylib (No such file or directory)
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libcepheiprefs.dylib (No such file or directory)
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libcephei.dylib (No such file or directory)
ldid.cpp(3004): _assert(): errno=2
error: /home/fede/Azule/toolchain/usr/bin/otool: can't open file: Payload/TuneIn Radio Pro.app/Frameworks/libhbangprefs.dylib (No such file or directory)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/Cephei.framework/ (No such device)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/CepheiUI.framework/ (No such device)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/CepheiPrefs.framework/ (No such device)
ldid.cpp(3008): _assert(): !flag_r
error: /home/fede/Azule/toolchain/usr/bin/otool: can't map file: Payload/TuneIn Radio Pro.app/Frameworks/CepheiUI.framework/ (No such device)
ID Successful
Re-Link Successful
Generating iPA...
Generated IPA at /home/fede/test//tunepro.ipa+ws.hbang.common_1.14_iphoneos-arm.deb.ipa

Please, any idea? Ipa not working....

THanks

**Comment by nicknitewolf** [comment]
Can you please update azule using the new install instructions and try again?

**Comment by Al4ise** [comment]
Should be fixed in the latest build.
