### ISSUE TITLE
Dozens of incorrect escape/quotation causes bad handing of special paths

### ISSUE THREAD

**Issue by ViRb3** [Al4ise/Azule#45]
Please consider installing [ShellCheck](https://www.shellcheck.net) ([VSCode extension](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck)) and running it against your scripts. There are dozens of cases where quotations are misused and/or text is not properly escaped, resulting in bad handling of any file name or path that has a space or other non-standard symbol. If you want to go further, the tool reports over 100 additional potential issues. Not to despair, ShellCheck provides really detailed explanations of each issue with clear examples. It will be a great way to make your project more robust.

**Comment by Al4ise** [comment]
Thanks, will check it out

**Comment by nicknitewolf** [comment]
Ah nice. thanks for the suggestion!
