### ISSUE TITLE
Can"t inject more than 1 tweaks

### ISSUE THREAD

**Issue by elzari** [Al4ise/Azule#50]
With latests ios versions only injects 1 tweak, i put path tweak file.deb "space" path tweak file.deb ...and gives me error No Set Home..

could you fix it please? 

Thanks again a lot bro.

**Comment by nicknitewolf** [comment]
> With latests ios versions only injects 1 tweak, i put path tweak file.deb "space" path tweak file.deb ...and gives me error No Set Home..
> 
> could you fix it please?
> 
> Thanks again a lot bro.

Can you run the command with `-v` paste the full error log here?

**Comment by Al4ise** [comment]
> With latests ios versions only injects 1 tweak, i put path tweak file.deb "space" path tweak file.deb ...and gives me error No Set Home..
> 
> 
> 
> could you fix it please? 
> 
> 
> 
> Thanks again a lot bro. 

Which jailbreak are you running?

**Comment by bdashore3** [comment]
This has also happened to me, when I try to inject a second tweak (by entering 1 on the arguments prompt)

**Comment by bdashore3** [comment]
Here's the log from my terminal with verbose mode enabled, the verbose mode doesn't help as the main menu is the problem here

[Log](https://katb.in/kat7389)

**Comment by elzari** [comment]
Sorry but i"m on holidays. 

Ipad Pro 13.5 un 0ver 6.2.0.

**Comment by Al4ise** [comment]
> This has also happened to me (on macOS), when I try to inject a second tweak (by entering 1 on the arguments prompt)

You are supposed to drag and drop all the files at once. It won't allow you to trigger the menu a second time for a reason

**Comment by bdashore3** [comment]
> 
> 
> > This has also happened to me (on macOS), when I try to inject a second tweak (by entering 1 on the arguments prompt)
> 
> You are supposed to drag and drop all the files at once. It won't allow you to trigger the menu a second time for a reason

I tried that previously and the utility took all 4 paths as one string. Here's the [log](https://katb.in/fur7580).

However, when I provided the arguments directly in the command, azule took the paths separately and successfully completed.

**Comment by Al4ise** [comment]
Okay, I'll look into it. Thanks for reporting

**Comment by Al4ise** [comment]
> > > This has also happened to me (on macOS), when I try to inject a second tweak (by entering 1 on the arguments prompt)
> > 
> > 
> > You are supposed to drag and drop all the files at once. It won't allow you to trigger the menu a second time for a reason
> 
> I tried that previously and the utility took all 4 paths as one string. Here's the [log](https://katb.in/fur7580).
> 
> However, when I provided the arguments directly in the command, azule took the paths separately and successfully completed.

fixed

**Comment by bdashore3** [comment]
Works :)

Feel free to close this issue.

**Comment by elzari** [comment]
Yes, thanks for the fix, works now for me in 0.1-6. 🙏🏻

**Comment by Al4ise** [comment]
> Yes, thanks for the fix, works now for me in 0.1-6. 🙏🏻

Great then
