### ISSUE TITLE
Can’t decrypt apps with flexdecrypt

### ISSUE THREAD

**Issue by DragonightFury** [Al4ise/Azule#51]
On the latest iOS version I can’t decrypt apps properly using flexdecrypt. When decrypting process is finished, $ipadir seems to be just BundleID of the package you selected, so nothing happens after that. It works, however, when you decrypt binary manually

**Comment by Al4ise** [comment]
try running with the -m arguement

**Comment by Al4ise** [comment]
Can you try with the latest build?

**Comment by DragonightFury** [comment]
The thing is, I need specific app version (Spotify v8.6.42). And yeah, on the latest build it says "App Couldn't be Decrypted". By the way, I can't really do anything with Spotify at all - there are troubles with WatchPlaceholder which I can't properly solve
![IMG_2161](https://user-images.githubusercontent.com/37414171/129712413-5652b78b-2595-42d2-9e32-661c3f18a950.PNG)

**Comment by ARDEACT** [comment]
I have the same issue too, used -m argument and flexdecrypted. App I was using is Sankaku (ichan_3.7.ipa)

**Comment by Al4ise** [comment]
should be fixed in 0.1.9. run azule with -e or -w and it should work just fine

**Comment by ARDEACT** [comment]
> should be fixed in 0.1.9. run azule with -e or -w and it should work just fine

Tried again but says app is encrypted. Is there really no way if it's encrypted?

**Comment by Al4ise** [comment]
no, there is not. try decrypting it first. It shouldn't be too hard

**Comment by Al4ise** [comment]
> > should be fixed in 0.1.9. run azule with -e or -w and it should work just fine
> 
> Tried again but says app is encrypted. Is there really no way if it's encrypted?

i mean you can try running with the -r arguement on 0.2.0, but the chance of it working is really slim
