### ISSUE TITLE
Run setup-azule again

### ISSUE THREAD

**Issue by isthismarvin** [Al4ise/Azule#54]
When running `setup-azule` it successfully downloads all Cydia files, but when trying to create the ipa it gives an error saying that some tools are missing and that I should run `setup-azule` again. Doing so does nothing.

**Comment by Al4ise** [comment]
do you have xcode cli tools installed?

**Comment by isthismarvin** [comment]
I’m using Ubuntu 20.04

**Comment by Al4ise** [comment]
Oh. Then can you send me a screenshot of your $AZULE folder? Its likely in ~/Azule

**Comment by isthismarvin** [comment]
![azule_fs](https://user-images.githubusercontent.com/42657762/130226428-48fd8cff-4b95-42c1-9e4c-d37d929f03b4.png)
Do you mean this folder?

**Comment by Al4ise** [comment]
hm.. can you run azule with -v and send me the output then? like 'azule [arguements] -v'

**Comment by isthismarvin** [comment]
![azule_fs](https://user-images.githubusercontent.com/42657762/130227094-509fafbc-d909-4d77-852f-d2dbf5e9e815.png)

Here you go

**Comment by Al4ise** [comment]
I'll look into it in a bit. Meanwhile you can try running azule in CLI mode

**Comment by isthismarvin** [comment]
How do I do that?

**Comment by Al4ise** [comment]
run azule -h and it will show you the options

**Comment by isthismarvin** [comment]
```
isthis@WIN-GM9DUEDGS9T:~/Azule$ azule -n Isaac -i /home/isthis/Azule/input/isaac.ipa -f com.spark.nomoresmallapps -o /home/isthis/Azule/output -v

iPA will be written to /home/isthis/Azule/output/Isaac.ipa
/tmp/tmp.uPeU8Zs3xD/18679/Tweak has been created
Path to iPA is /home/isthis/Azule/input/isaac.ipa
Extracting iPA...
IPA extracted
App executable is Payload/Rebirth iOS.app/Rebirth iOS
Fetching com.spark.nomoresmallapps...
Fetched com.spark.nomoresmallapps
Extracting com.spark.nomoresmallapps...
com.spark.nomoresmallapps extracted
Copied NoMoreSmallApps.bundle to app directory
ID Successful
Re-Link Successful
Hooking Library not downloaded, please run setup-azule.
```

Also not working... I hope you'll find the problem <3

**Comment by Al4ise** [comment]
can you run "rm -rf $AZULE", restart your terminal, and then run the setup again?

**Comment by isthismarvin** [comment]
Now it's working! That was a fast fix. Thank you
