### ISSUE TITLE
It is support for Inject .m/.xm?

### ISSUE THREAD

**Issue by Am1nCmd** [Al4ise/Azule#56]
hello there, thx for new update, is is huge update

just little question, it's support for injecting .m/.xm files like theos way?
or its only .deb and .dylib files?

Thank you in advance

**Comment by Al4ise** [comment]
well .m and .xm files need to be compiled before they are used, and compiling some tweaks may sometimes be quite the pain in the ass. So no, importing such files isn't supported and won't be supported in the near future

**Comment by Am1nCmd** [comment]
alright, thank you for this information

On 23 Aug 2021, at 17.54, Martin Pelteshki ***@***.******@***.***>> wrote:



well .m and .xm files need to be compiled before they are used, and compiling some tweaks may sometimes be quite the pain in the ass. So no, importing such files isn't supported and won't be supported in the near future
