### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by theghgh** [Al4ise/Azule#58]
Hey! I’ve tried setting up Azule on 3 different devices and keep getting this error. Screenshot is of Ubuntu 21.04 but I’ve also tried 20.04 and MacOS Big Sur (non M1)

![5B6BD4C1-67C8-42D7-BF27-9882B55F2D56](https://user-images.githubusercontent.com/43161110/132140690-43c672c8-f22e-4077-9336-1f2c14bcac2b.png)

**Comment by theghgh** [comment]
Also occurs when specifying the deb and other arguments but it’s hard to type on phone so I just used the menu for screenshot

**Comment by Al4ise** [comment]
fixed

**Comment by theghgh** [comment]
> fixed

![B852952B-F7A8-4C18-A96B-93A316E5BDD2](https://user-images.githubusercontent.com/43161110/132141967-8f8b34d1-589a-47b1-b061-eac0114b8548.jpeg)

also getting this, only occurs on Ubuntu not max

the mac is on a vps so I can’t really use it a lot without overpaying

**Comment by Al4ise** [comment]
fixed in the newest build

**Comment by theghgh** [comment]
> fixed in the newest build

Thanks!

Also I injected a tweak which usually needs to be enabled in settings (amazonite if you’d want to try) but I’m not sure how to enable the tweak

I injected the dylib inside mobilesubstrate folder so not sure if that’s enough

**Comment by Al4ise** [comment]
If a tweak uses a preference bundle, it can't really be injected into an ipa, sorry
