### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by THe-cat8567** [Al4ise/Azule#66]
If curl is aliased as so: `alias curl='curl -L -O` (like in `~/.profile` or `~/.bashrc`) , it breaks installation with the following error:

`Fetching toolchain...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   176  100   176    0     0    242      0 --:--:-- --:--:-- --:--:--   241
100   680  100   680    0     0    705      0 --:--:-- --:--:-- --:--:--   705
100  102M  100  102M    0     0  3441k      0  0:00:30  0:00:30 --:--:-- 3933k
Downloading CydiaSubstrate...
ar: substrate.deb: No such file or directory
tar (child): data.tar.lzma: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'CydiaSubstrate.framework/CydiaSubstrate': No such file or directory
rm: cannot remove 'CydiaSubstrate.framework/Headers/CydiaSubstrate.h': No such file or directory
rsync: link_stat "/tmp/tmp.nB5yWQTejA/libsubstrate.dylib" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
Downloaded libsubstrate.dylib
mv: cannot stat 'libsubstrate.dylib': No such file or directory
mv: cannot stat 'substrate.h': No such file or directory
mv: cannot stat 'CydiaSubstrate.framework': No such file or directory
error: unable to read /home/me/Azule/lib/CydiaSubstrate.framework/Info.plist
Downloaded CydiaSubstrate.framework
Downloading Substitute...
ar: substitute.deb: No such file or directory
tar (child): data.tar.lzma: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat 'libsubstitute.dylib': No such file or directory
Downloaded Substitute`. I believe the cause of the error is in these lines
https://github.com/Al4ise/Azule/blob/main/azule-functions#L65
https://github.com/Al4ise/Azule/blob/main/azule-functions#L82
https://github.com/Al4ise/Azule/blob/main/azule-functions#L82
as that is when curl is called. This is rather easy to solve by using `command curl` in the code or just having the user unset their `curl` alias but this might confuse users new to the shell.

**Comment by Al4ise** [comment]
when might curl be aliased as such? sorry for the late response
