### ISSUE TITLE
Couldn't strip codesign

### ISSUE THREAD

**Issue by ibrahimqatar** [Al4ise/Azule#68]
When I try to inject Plus for Instagram, I get this error (same error for rocket for instagram):

Extracting iPA...
IPA extracted
Extracting prasa.plusfi_2.38_iphoneos-arm.deb...
Extracted prasa.plusfi_2.38_iphoneos-arm.deb
rsync: push_dir#3 "/private/var/folders/jx/sbpvp5p15r3_l859by6rnw040000gn/T/tmp.fYnlp0S8/4038/@loader_path" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at /System/Volumes/Data/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(581) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /System/Volumes/Data/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]
Copied PlusBundle.bundle to app directory
Couldn't strip codesign from PlusForInstagram.dylib

It worked fine with other tweaks, I'm using an M1 Max machine if that makes any difference.

any idea?

UPDATE:

I tried updating rsync using "arch -x86_64 brew install rsync" and I got a slightly different output but with the same result at the end.

Extracting iPA...
IPA extracted
Extracting prasa.plusfi_2.38_iphoneos-arm.deb...
Extracted prasa.plusfi_2.38_iphoneos-arm.deb
rsync: [Receiver] change_dir#3 "/private/var/folders/jx/sbpvp5p15r3_l859by6rnw040000gn/T/tmp.DIMfwgM3/30199/@loader_path" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(826) [Receiver=3.2.3]
Copied PlusBundle.bundle to app directory
Couldn't strip codesign from PlusForInstagram.dylib

**Comment by strejda603** [comment]
I have the same issue (macOS Monterey)

**Comment by Al4ise** [comment]
should be fixed now
