### ISSUE TITLE
Couldn't strip codesign from dylib

### ISSUE THREAD

**Issue by itsmylife44** [Al4ise/Azule#70]
Extracting iPA...
IPA extracted
Removing Extensions...
Removed Extensions
Removing Watch App...
Removed Watch App
Couldn't strip codesign from dylib

directly from jailbroken iphone last version

**Comment by Al4ise** [comment]
could you give me the full -v output?

**Comment by itsmylife44** [comment]
iPhone:~ root# azule -i "/Deezer.ipa" -o "/" -f "/Deezelife.dylib" -u -e -w -r -v
iPA will be written to //Deezer.ipa+Deezelife.dylib.ipa
/tmp/tmp.BTcbhxGbjd/4411/Tweak has been created
Path to iPA is /Deezer.ipa
Extracting iPA...
IPA extracted
Removing Extensions...
Removed Extensions
Removing Watch App...
Removed Watch App
App executable is Payload/Deezer.app/Deezer
App rpath is Payload/Deezer.app/Frameworks
/Deezelife.dylib will be imported
Copied Deezelife.dylib to work directory
Copied Deezelife.dylib to app directory
Couldn't strip codesign from Deezelife.dylib

**Comment by Al4ise** [comment]
1. What is the directory where your files are?
2. Don't run azule as root

**Comment by itsmylife44** [comment]
i noticed that if i use a ".deb" file , its working , if i even use an extracted dylib file from .deb , the error  output is Couldn't strip codesign .

i've tryed out of root folder and without root permissions .

**Comment by Al4ise** [comment]
Could you send me the ipa and dylib you are using? I can't get to replicate the issue

**Comment by itsmylife44** [comment]
also decrypting with felxdecrypt isn't working . 

```
iPhone: azule -i "com.spotify.client" -o "/var/mobile/Documents/" -u -v -e -w -r -x "xxx@xxx" -g
iPA will be written to /var/mobile/Documents//com.spotify.client.ipa
/tmp/tmp.X2CVXvaVE7/31932/Tweak has been created
Password for Apple ID: ==> ℹ️    [Info] Querying the iTunes store for 'com.spotify.client'...
==> ℹ️   [Info] Authenticating with the App Store...
==> ℹ️   [Info] Authenticated as 'xxx'.
==> ℹ️   [Info] Requesting a signed copy of '324684580' from the App Store...
==> ℹ️   [Info] Downloading app package... [100%]
==> ℹ️   [Info] Saved app package to com.spotify.client_324684580_v8.6.84_657.ipa.
==> ℹ️   [Info] Applying patches...
==> ℹ️   [Info] Done.
Installing com.spotify.client_324684580_v8.6.84_657.ipa ...
Preparing App...
Removing Extensions...
Removed Extensions
Removing Watch App...
Removed Watch App
Decrypting App...
Couldn't Decrypt EncoreFoundation-FW
Couldn't Decrypt Spotify
Decrypted App
Decrypted com.spotify.client
App executable is Payload/Spotify.app/Spotify
App rpath is Payload/Spotify.app/Frameworks
The specified iPA doesn't have UISupportedDevices
Generating iPA...
Generated IPA at /var/mobile/Documents//com.spotify.client.ipa
```

**Comment by Al4ise** [comment]
What iPhone are you using? Flexdecrypt is pretty hit or miss and I'm still not sure why

**Comment by itsmylife44** [comment]
iphone 7 ios 14.6 checkra1n

**Comment by itsmylife44** [comment]
Also with bfdecrypt it isn't working . 
I assume it's a problem related to ios 14.6 .

```
iPhone-di-Jan: azule -i "com.spotify.client" -o "/var/mobile/Documents/" -u -v -e -w -r -x "xxx@xx.com"
iPA will be written to /var/mobile/Documents//com.spotify.client.ipa
/tmp/tmp.NudXTBivSg/25728/Tweak has been created
Password for Apple ID: ==> ℹ️    [Info] Querying the iTunes store for 'com.spotify.client'...
==> ℹ️   [Info] Authenticating with the App Store...
==> ℹ️   [Info] Authenticated as 'xxx'.
==> ℹ️   [Info] Requesting a signed copy of '324684580' from the App Store...
==> ℹ️   [Info] Downloading app package... [100%]
==> ℹ️   [Info] Saved app package to com.spotify.client_324684580_v8.6.84_480.ipa.
==> ℹ️   [Info] Applying patches...
==> ℹ️   [Info] Done.
Installing com.spotify.client_324684580_v8.6.84_480.ipa ...
```

and it's still happening nothing . 

settings toggle on bfdecrypt is opening , i toggle an app , reopen the app but nothing happens , to i think it's bfdecrypt doesnt support 14.6

**Comment by Al4ise** [comment]
no,the bfdecrypt thing was my bad, fixed in the latest version

**Comment by Al4ise** [comment]
Also may I ask which bootstrap you are running, Elcubratus or Procursus, as flexdecrypt seems to work perfectly on my end (iPhone 7, ios 14.6, same as yours). It may be because I am on odysseyra1n?

**Comment by Al4ise** [comment]
either ways, could you try running -g with this build? It won't fix much, but it should give you more detailed error logs
[Azule-iOS_debug.deb.zip](https://github.com/Al4ise/Azule/files/7777059/Azule-iOS_debug.deb.zip)

**Comment by itsmylife44** [comment]
```
- iPhone : azule -i "com.spotify.client" -o "/var/mobile/Documents/" -f "/var/mobile/Documents/Spotilife.dylib" -u -v -e -w -r -x "xxx@xxx" -g
- iPA will be written to /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
- /tmp/tmp.z52Rw6VSuH/26481/Tweak has been created
- Password for Apple ID: ==> ℹ️    [Info] Querying the iTunes store for 'com.spotify.client'...
- ==> ℹ️   [Info] Authenticating with the App Store...
- ==> ℹ️   [Info] Authenticated as 'xxx'.
- ==> ℹ️   [Info] Requesting a signed copy of '324684580' from the App Store...
- ==> ℹ️   [Info] Downloading app package... [100%]
- ==> ℹ️   [Info] Saved app package to com.spotify.client_324684580_v8.6.84_280.ipa.
- ==> ℹ️   [Info] Applying patches...
- ==> ℹ️   [Info] Done.
- Installing com.spotify.client_324684580_v8.6.84_280.ipa ...
- Preparing App...
- Removing Extensions...
- Removed Extensions
- Removing Watch App...
- Removed Watch App
- Decrypting App...
- Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
- Couldn't Decrypt EncoreFoundation-FW
- Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
- Couldn't Decrypt Spotify
- Decrypted App
- Decrypted com.spotify.client
- App executable is Payload/Spotify.app/Spotify
- App rpath is Payload/Spotify.app/Frameworks
- /var/mobile/Documents/Spotilife.dylib will be imported
- Copied Spotilife.dylib to work directory
- Copied Spotilife.dylib to app directory
- Codesign stripped from Spotilife.dylib
- ID Successful
- Injected Spotilife.dylib
- The specified iPA doesn't have UISupportedDevices
- Generating iPA...
- Generated IPA at /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
- 
```

**Comment by itsmylife44** [comment]
it would also be cool to add an option to inject substratum or not :)

**Comment by Al4ise** [comment]
> ```
> 
> - iPhone : azule -i "com.spotify.client" -o "/var/mobile/Documents/" -f "/var/mobile/Documents/Spotilife.dylib" -u -v -e -w -r -x "xxx@xxx" -g
> 
> - iPA will be written to /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
> 
> - /tmp/tmp.z52Rw6VSuH/26481/Tweak has been created
> 
> - Password for Apple ID: ==> ℹ️    [Info] Querying the iTunes store for 'com.spotify.client'...
> 
> - ==> ℹ️   [Info] Authenticating with the App Store...
> 
> - ==> ℹ️   [Info] Authenticated as 'xxx'.
> 
> - ==> ℹ️   [Info] Requesting a signed copy of '324684580' from the App Store...
> 
> - ==> ℹ️   [Info] Downloading app package... [100%]
> 
> - ==> ℹ️   [Info] Saved app package to com.spotify.client_324684580_v8.6.84_280.ipa.
> 
> - ==> ℹ️   [Info] Applying patches...
> 
> - ==> ℹ️   [Info] Done.
> 
> - Installing com.spotify.client_324684580_v8.6.84_280.ipa ...
> 
> - Preparing App...
> 
> - Removing Extensions...
> 
> - Removed Extensions
> 
> - Removing Watch App...
> 
> - Removed Watch App
> 
> - Decrypting App...
> 
> - Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
> 
> - Couldn't Decrypt EncoreFoundation-FW
> 
> - Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
> 
> - Couldn't Decrypt Spotify
> 
> - Decrypted App
> 
> - Decrypted com.spotify.client
> 
> - App executable is Payload/Spotify.app/Spotify
> 
> - App rpath is Payload/Spotify.app/Frameworks
> 
> - /var/mobile/Documents/Spotilife.dylib will be imported
> 
> - Copied Spotilife.dylib to work directory
> 
> - Copied Spotilife.dylib to app directory
> 
> - Codesign stripped from Spotilife.dylib
> 
> - ID Successful
> 
> - Injected Spotilife.dylib
> 
> - The specified iPA doesn't have UISupportedDevices
> 
> - Generating iPA...
> 
> - Generated IPA at /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
> 
> - 
> 
> ```

It's kind of a long shot but could you clear your app switcher completely and try again?

**Comment by Al4ise** [comment]
> it would also be cool to add an option to inject substratum or not :)

I'm not sure it's necessary, it injects substrate only when it is required by the tweaks you are injecting

**Comment by itsmylife44** [comment]
> > it would also be cool to add an option to inject substratum or not :)
> 
> I'm not sure it's necessary, it injects substrate only when it is required by the tweaks you are injecting

Fact is , if i install the tweak through sileo , and select from libhooker substrate Compatibility instead of libhooker , the app didn't crash , if i select libhooker , the app crash , that means that the ipa that i would inject need substrate , for that it would be cool to have an option to inject it or not .

**Comment by itsmylife44** [comment]
> > ```
> > 
> > - iPhone : azule -i "com.spotify.client" -o "/var/mobile/Documents/" -f "/var/mobile/Documents/Spotilife.dylib" -u -v -e -w -r -x "xxx@xxx" -g
> > 
> > - iPA will be written to /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
> > 
> > - /tmp/tmp.z52Rw6VSuH/26481/Tweak has been created
> > 
> > - Password for Apple ID: ==> ℹ️    [Info] Querying the iTunes store for 'com.spotify.client'...
> > 
> > - ==> ℹ️   [Info] Authenticating with the App Store...
> > 
> > - ==> ℹ️   [Info] Authenticated as 'xxx'.
> > 
> > - ==> ℹ️   [Info] Requesting a signed copy of '324684580' from the App Store...
> > 
> > - ==> ℹ️   [Info] Downloading app package... [100%]
> > 
> > - ==> ℹ️   [Info] Saved app package to com.spotify.client_324684580_v8.6.84_280.ipa.
> > 
> > - ==> ℹ️   [Info] Applying patches...
> > 
> > - ==> ℹ️   [Info] Done.
> > 
> > - Installing com.spotify.client_324684580_v8.6.84_280.ipa ...
> > 
> > - Preparing App...
> > 
> > - Removing Extensions...
> > 
> > - Removed Extensions
> > 
> > - Removing Watch App...
> > 
> > - Removed Watch App
> > 
> > - Decrypting App...
> > 
> > - Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
> > 
> > - Couldn't Decrypt EncoreFoundation-FW
> > 
> > - Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
> > 
> > - Couldn't Decrypt Spotify
> > 
> > - Decrypted App
> > 
> > - Decrypted com.spotify.client
> > 
> > - App executable is Payload/Spotify.app/Spotify
> > 
> > - App rpath is Payload/Spotify.app/Frameworks
> > 
> > - /var/mobile/Documents/Spotilife.dylib will be imported
> > 
> > - Copied Spotilife.dylib to work directory
> > 
> > - Copied Spotilife.dylib to app directory
> > 
> > - Codesign stripped from Spotilife.dylib
> > 
> > - ID Successful
> > 
> > - Injected Spotilife.dylib
> > 
> > - The specified iPA doesn't have UISupportedDevices
> > 
> > - Generating iPA...
> > 
> > - Generated IPA at /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
> > 
> > - 
> > ```
> 
> It's kind of a long shot but could you clear your app switcher completely and try again?

nothing changed .. wired

**Comment by Al4ise** [comment]
> > > it would also be cool to add an option to inject substratum or not :)
> 
> > 
> 
> > I'm not sure it's necessary, it injects substrate only when it is required by the tweaks you are injecting
> 
> 
> 
> Fact is , if i install the tweak through sileo , and select from libhooker substrate Compatibility instead of libhooker , the app didn't crash , if i select libhooker , the app crash , that means that the ipa that i would inject need substrate , for that it would be cool to have an option to inject it or not . 

Can you give me an example for such a tweak?

**Comment by itsmylife44** [comment]
> > > > it would also be cool to add an option to inject substratum or not :)
> > 
> > 
> > > 
> > 
> > 
> > > I'm not sure it's necessary, it injects substrate only when it is required by the tweaks you are injecting
> > 
> > 
> > Fact is , if i install the tweak through sileo , and select from libhooker substrate Compatibility instead of libhooker , the app didn't crash , if i select libhooker , the app crash , that means that the ipa that i would inject need substrate , for that it would be cool to have an option to inject it or not .
> 
> Can you give me an example for such a tweak?

can we talk on discord maybe ? it should be better :)

**Comment by Al4ise** [comment]
> > > ```
> 
> > > 
> 
> > > - iPhone : azule -i "com.spotify.client" -o "/var/mobile/Documents/" -f "/var/mobile/Documents/Spotilife.dylib" -u -v -e -w -r -x "xxx@xxx" -g
> 
> > > 
> 
> > > - iPA will be written to /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
> 
> > > 
> 
> > > - /tmp/tmp.z52Rw6VSuH/26481/Tweak has been created
> 
> > > 
> 
> > > - Password for Apple ID: ==> ℹ️    [Info] Querying the iTunes store for 'com.spotify.client'...
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Authenticating with the App Store...
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Authenticated as 'xxx'.
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Requesting a signed copy of '324684580' from the App Store...
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Downloading app package... [100%]
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Saved app package to com.spotify.client_324684580_v8.6.84_280.ipa.
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Applying patches...
> 
> > > 
> 
> > > - ==> ℹ️   [Info] Done.
> 
> > > 
> 
> > > - Installing com.spotify.client_324684580_v8.6.84_280.ipa ...
> 
> > > 
> 
> > > - Preparing App...
> 
> > > 
> 
> > > - Removing Extensions...
> 
> > > 
> 
> > > - Removed Extensions
> 
> > > 
> 
> > > - Removing Watch App...
> 
> > > 
> 
> > > - Removed Watch App
> 
> > > 
> 
> > > - Decrypting App...
> 
> > > 
> 
> > > - Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
> 
> > > 
> 
> > > - Couldn't Decrypt EncoreFoundation-FW
> 
> > > 
> 
> > > - Error: mremap_encryptedFailed(segment: "__TEXT", error: "#12: Cannot allocate memory")
> 
> > > 
> 
> > > - Couldn't Decrypt Spotify
> 
> > > 
> 
> > > - Decrypted App
> 
> > > 
> 
> > > - Decrypted com.spotify.client
> 
> > > 
> 
> > > - App executable is Payload/Spotify.app/Spotify
> 
> > > 
> 
> > > - App rpath is Payload/Spotify.app/Frameworks
> 
> > > 
> 
> > > - /var/mobile/Documents/Spotilife.dylib will be imported
> 
> > > 
> 
> > > - Copied Spotilife.dylib to work directory
> 
> > > 
> 
> > > - Copied Spotilife.dylib to app directory
> 
> > > 
> 
> > > - Codesign stripped from Spotilife.dylib
> 
> > > 
> 
> > > - ID Successful
> 
> > > 
> 
> > > - Injected Spotilife.dylib
> 
> > > 
> 
> > > - The specified iPA doesn't have UISupportedDevices
> 
> > > 
> 
> > > - Generating iPA...
> 
> > > 
> 
> > > - Generated IPA at /var/mobile/Documents//com.spotify.client+Spotilife.dylib.ipa
> 
> > > 
> 
> > > - 
> 
> > > ```
> 
> > 
> 
> > It's kind of a long shot but could you clear your app switcher completely and try again?
> 
> 
> 
> nothing changed .. wired 

hm... then may I ask again, are you running Elcubratus or Procursus?

**Comment by Al4ise** [comment]
> > > > > it would also be cool to add an option to inject substratum or not :)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I'm not sure it's necessary, it injects substrate only when it is required by the tweaks you are injecting
> 
> > > 
> 
> > > 
> 
> > > Fact is , if i install the tweak through sileo , and select from libhooker substrate Compatibility instead of libhooker , the app didn't crash , if i select libhooker , the app crash , that means that the ipa that i would inject need substrate , for that it would be cool to have an option to inject it or not .
> 
> > 
> 
> > Can you give me an example for such a tweak?
> 
> 
> 
> can we talk on discord maybe ? it should be better :)

yeah sounds like a good idea. I'm Moonlight Jesus#0415 there

**Comment by itsmylife44** [comment]
> 

i didn't find you , here is mine : xSpaM#9286

**Comment by Al4ise** [comment]
Sent you a request
