### ISSUE TITLE
bash_profile edit on ubuntu

### ISSUE THREAD

**Issue by dayanch96** [Al4ise/Azule#72]
3. Import azule-functions to run azule commands
For bash run the following command:

echo "source $HOME/Azule/azule-functions" >> ~/.profile

This will not work for ubuntu.

Workaround:
1. install nano
2. type sudo nano ~/.bash_profile
3. add 'source $HOME/Azule/azule-functions' and save file.

**Comment by Al4ise** [comment]
why wouldn't it work on ubuntu? I've tried it on Debian and it has worked just fine

**Comment by dayanch96** [comment]
> why wouldn't it work on ubuntu? I've tried it on Debian and it has worked just fine

for me, it doesn’t save string in bash_profile (tried restart terminal)

**Comment by Al4ise** [comment]
The file used is ~/.profile though, not ~/.bash_profile

**Comment by dayanch96** [comment]
Yeah, my bad, changed text. setup_azule never worked for me without it.

**Comment by Al4ise** [comment]
So.. does it work?

**Comment by dayanch96** [comment]
Yes. I think this problem occurs on freshly installed ubuntu. Anyway, it works now.

**Comment by Al4ise** [comment]
Great then
