### ISSUE TITLE
error: invalid app

### ISSUE THREAD

**Issue by binnichtaktiv** [Al4ise/Azule#73]
every time when i paste my ipa path i get te error app invalid. i tried an older version of azule but it still didn't work. The ipa was decrpyted with Crackerxi+

**Comment by Al4ise** [comment]
can you show me your terminal?

**Comment by binnichtaktiv** [comment]
![Uploading 4E75767A-2552-44F1-818F-BB01D44C3E39.png…]()

**Comment by binnichtaktiv** [comment]
![D0C11E5E-A464-4217-B8EF-AD3856F79E86](https://user-images.githubusercontent.com/96953964/147857945-dd0d8a04-a07e-46ed-a615-31fda208607b.png)

**Comment by Al4ise** [comment]
It is /var/mobile/...

**Comment by binnichtaktiv** [comment]
![1F92F01F-C57F-4668-92E3-67EE54F02F0A](https://user-images.githubusercontent.com/96953964/147858002-12f61a65-351e-481a-82dd-530a225c4dfa.png)

**Comment by binnichtaktiv** [comment]
have tried it with another ipa but the same

**Comment by Al4ise** [comment]
you need to put another / in the beginning of your path.

**Comment by binnichtaktiv** [comment]
Bruh I’m so sorry to waste your time😫 my fault

**Comment by Al4ise** [comment]
Haha no problem, it happens
