### ISSUE TITLE
Insufficient Arguements

### ISSUE THREAD

**Issue by davex2012** [Al4ise/Azule#74]
When trying to copy patch its always say Insufficient Arguements. Why?

**Comment by davex2012** [comment]
<img width="526" alt="Screenshot 2022-01-07 at 02 18 05" src="https://user-images.githubusercontent.com/15570883/148475557-d86c01ed-9bb9-4a87-b5d6-95484dd2503c.png">

**Comment by Al4ise** [comment]
i removed gui mode, run azule -h and it will show you the different options
