### ISSUE TITLE
error when injecting multiple tweaks

### ISSUE THREAD

**Issue by binnichtaktiv** [Al4ise/Azule#83]
when I inject 11 debs everything is fine but when I try 12  debs I always get an error no matter what deb I use. Is this a bug?
![IMG_0015](https://user-images.githubusercontent.com/96953964/155017048-77ff81ff-1400-4ae8-a260-13b2302e043a.PNG)
![IMG_0016](https://user-images.githubusercontent.com/96953964/155017052-bce4cfdb-9878-4e2a-965a-36fa8eb03c3f.PNG)
![IMG_0018](https://user-images.githubusercontent.com/96953964/155017180-445013eb-f600-4245-ade8-be492824a793.PNG)

and as you can see there is no mistake with the filenames. Idk whats the problem :(

**Comment by Al4ise** [comment]
I will look into it as soon as I have the time. Sorry for the late reply :/

**Comment by binnichtaktiv** [comment]
have you had time to look at it yet?😀

> I will look into it as soon as I have the time. Sorry for the late reply :/

have you had time to look at it yet?

**Comment by Al4ise** [comment]
you need to put a / before the var in the last filename you are specifying

**Comment by binnichtaktiv** [comment]
> you need to put a / before the var in the last filename you are specifying

Oh my bad. I’m sorry🥲

**Comment by Al4ise** [comment]
haha don’t worry, it happens to the best of us :)
