### ISSUE TITLE
App crashes upon installation

### ISSUE THREAD

**Issue by nn9dev** [Al4ise/Azule#84]
Hi, I'm trying to inject Spotilife (1.7a) into the latest Spotify version (8.7.8) both taken from official sources (julio's repo and decrypted with Cracker XI+ respectively). The injection process supposedly works just fine, but when I install and open the app (tested both with AppSync and AltStore), the app simply crashes. I've tried -j, -g, -S, and even .deb vs the raw .dylib, but to no avail. Is there something you think I may be doing wrong?

**Comment by binnichtaktiv** [comment]
The problem is that Spotilife doesnt support the latest Spotify version. When you want to inject Spotilife use Spotify version 8.6.42. This problem has nothing to do with Azule

**Comment by nn9dev** [comment]
Do you think you could elaborate further on that? I'm using that exact version (1.7a) on the latest version of Spotify (8.7.8) on my jailbroken iPhone SE 2020. Is it an issue with not liking it running while jailed? Checks for things that pass while jailed but not jailbroken?

**Comment by binnichtaktiv** [comment]
Ijulioverne isn’t active so he doesn’t update his tweaks anymore. Spotilife just doesn’t work with the latest Spotify version because the tweak is outdated. Try injecting with sideloadly if it still fails it’s the tweaks fault

**Comment by nn9dev** [comment]
I don't quite follow. I have Spotilife installed personally, right in front of me, and it is working just fine and dandy. On the very latest version of Spotify. So is the reason that it doesn't work jailed simply, "that's how it is?" Because it's absolutely not a tweak-not-being-compatible issue if I'm interpreting your statement the way I think it's supposed to be interpreted.

**Comment by binnichtaktiv** [comment]
For me it doesn’t work on the latest version. Send me a screenshot of Spotify homescreen. It should work jailed because there are a lot of Spotify ++ ipas with Spotilife injected

**Comment by nn9dev** [comment]
Well that's why I made an issue. Because it was working in one scenario but not in another. 

https://imgur.com/a/WGer2P0

**Comment by nn9dev** [comment]
I've been installing the generated .ipa on my own jailbroken phone to test. That ought to be using AppSync and thus not need a developer account of any sorts, but the issue still persisted.

**Comment by nn9dev** [comment]
That's the weird thing, it doesn't generate one, else I would've tried to diagnose it further myself. It doesn't report a crash in iOS's CrashReporter either. 

video:
https://imgur.com/a/VVlAuiN

**Comment by binnichtaktiv** [comment]
Try crashreporter from cokepokes

**Comment by nn9dev** [comment]
Absolutely nothing.

**Comment by Al4ise** [comment]
> Absolutely nothing.
> 
> 
Then i guess the problem has to be with the tweak
