### ISSUE TITLE
[Question] After closing YouTube and reopening, account is signed out

### ISSUE THREAD

**Issue by GreenglassT** [Al4ise/Azule#85]
Every time I close the YouTube app that has a few tweaks injected I am logged out of my YouTube account. I have the same problem with app extensions or without extensions. I'm confused as to why this is since uYou+ does not have this problem on jailed phones. 

Is this possible to fix?

**Comment by binnichtaktiv** [comment]
I think that has nothing to do with azule I think🤔

**Comment by Al4ise** [comment]
Not a problem with azule. You need some sort of tweak that fixes that. As far as I know, cercube and uyou are among the few that do that

**Comment by GreenglassT** [comment]
I found a fix!! I wasn't sure if this was an Azule thing or just a sideloading problem. Thank you!
