### ISSUE TITLE
deb no be inject 

### ISSUE THREAD

**Issue by for40255** [Al4ise/Azule#86]
deb cant be inject 
only use .dylib can be inject

![3A37A3C2-8A02-44D9-A3DE-355D53F9AAF5](https://user-images.githubusercontent.com/58337638/158038464-3d88028e-2fc3-445e-9fa9-b0a13d3a024a.jpeg)

![A3779A04-BBA3-40B8-87CB-FAD5745A075C](https://user-images.githubusercontent.com/58337638/158038468-7e8cc374-a839-4e00-93f3-72e42096510e.jpeg)

![09633B80-C792-44A0-9071-F71C242D94AE](https://user-images.githubusercontent.com/58337638/158038483-79bf0ead-97f3-4d2e-aa6c-b0e6ece3a953.jpeg)
![A09E43C5-54E1-452D-ACF8-23AFAC71CE6C](https://user-images.githubusercontent.com/58337638/158038486-21b08800-067d-446c-b815-1b044abc96c2.jpeg)

**Comment by Al4ise** [comment]
Could you send me the DEB? I think I know what the problem might be

**Comment by for40255** [comment]
> 你能把DEB发给我吗？我想我知道问题可能是什么

**Comment by for40255** [comment]
> Could you send me the DEB? I think I know what the problem might be
https://drive.google.com/file/d/1MP2p1HaNOVyq2m9zjhJxMbcZVix-DFFO/view?usp=drivesdk

thanks for your reply

**Comment by for40255** [comment]
> Could you send me the DEB? I think I know what the problem might be

The problem should be here

![B30CE99B-4F57-4126-8403-366D1250124E](https://user-images.githubusercontent.com/58337638/158060600-fe423b18-9c0f-4b8d-8eb5-67a6d789a25c.jpeg)
![968321C4-85CB-4CC3-A539-9AB6ACAB9D2F](https://user-images.githubusercontent.com/58337638/158060608-3a45b3b4-0c94-4354-ba3d-b5f031a7eb78.jpeg)

**Comment by Al4ise** [comment]
fixed, sorry for the delay

**Comment by for40255** [comment]
> fixed, sorry for the delay

Taank for the update!
