### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by NexIsStrange** [Al4ise/Azule#88]
When I try to run the setup-azule command, it says command not found, and when I try to install the .deb, it says unable to install...The following packages have unmet dependencies:

I already installed all of the things listed on the tutorial

**Comment by Al4ise** [comment]
1. You should try killing your terminal window after importing azule-functions to .profile/.zprofile.

2. You should install the missing packages manually :​/. It's a hassle, I know, but it is an issue with Procursus. There's not much I can do about it

**Comment by NexIsStrange** [comment]
the echo thing doesn't seem to do anything

**Comment by NexIsStrange** [comment]
And ohh, it doesn't say which ones are missing. and I already tried to install everything manually, but all of them said that its already installed
