### ISSUE TITLE
Injected tweaks do not work.

### ISSUE THREAD

**Issue by calvincorrieri** [Al4ise/Azule#91]
I am sure I have everything installed correctly. I have run through the process many times. I have received zero error messages. But no matter what I try, when I install the app, none of the tweaks are present. Can anyone please help me with this?

**Comment by royerlraph79** [comment]
I second this. No error, but no tweak injected either.

**Comment by Lizynz** [comment]
I installed the previous version until I found another solution. New version doesn't work.

**Comment by Al4ise** [comment]
Could you tell me what app you are using and what tweak you are injecting into it?

**Comment by royerlraph79** [comment]
I tried injecting tweaks into YouTube and TikTok, same tweaks as usual, just updating the apps.

**Comment by Al4ise** [comment]
> I installed the previous version until I found another solution. New version doesn't work.

could you tell me which version worked?

**Comment by Lizynz** [comment]
> > I installed the previous version until I found another solution. New version doesn't work.
> 
> could you tell me which version worked?

iOS v0.5.8

**Comment by Al4ise** [comment]
should be fixed now

**Comment by Al4ise** [comment]
Please reopen if issues persist
