### ISSUE TITLE
line 74: plutil: command not found

### ISSUE THREAD

**Issue by giangcoi89** [Al4ise/Azule#92]
When i try inject dylib, get error

anony@DESKTOP-665CEPV:~$ azule -n Test -i ~/ipa/youtube.ipa -o ~/done -f ~/deb/me.alfhaily.cercube_5.3.8_iphoneos-arm.deb
[*] Azule is Up to Date
[*] Extracting iPA...
[*] IPA extracted
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
/usr/local/bin/azule: line 74: plutil: command not found
[*] Couldn't set app executable
anony@DESKTOP-665CEPV:~$

**Comment by giangcoi89** [comment]
When i try update get error
anony@DESKTOP-665CEPV:~$ azule -R
[*] Azule is Up to Date
[*] Fetching toolchain...
[*] Fetched Toolchain
[*] Setting Up Toolchain...
[*] Set Up Toolchain
[*] Downloading CydiaSubstrate...
/usr/local/bin/azule: line 450: plutil: command not found
[*] Downloaded CydiaSubstrate.framework
[*] Downloading Substitute...
[*] Downloaded Substitute
[*] No Output Directory Specified. Run 'azule -h' for help
anony@DESKTOP-665CEPV:~$

**Comment by Al4ise** [comment]
fixed in the latest version
