### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Ditpo** [Al4ise/Azule#95]
The installation instructions for macOS say that Xcode is needed, but that’s a hefty 13 GB+ Download.

I just installed the Command Line Tools from here: [https://developer.apple.com/download/all/](https://developer.apple.com/download/all/) and Azule seems to be working fine, maybe something to consider.

Unless I am missing something of course.

**Comment by Ditpo** [comment]
That’s exactly what I mean.

There was one instance where that did not work though, so maybe put the link in a „troubleshooting“-section or something like that.

**Comment by Al4ise** [comment]
i may just list it as an option in the installation instructions that people can just download the CLI tools from apple's website

**Comment by cameroncc** [comment]
And I've been using Azule just fine without having Xcode installed on my Mac. I'm running Big Sur

**Comment by Al4ise** [comment]
fair enough, changing it in a second
