### ISSUE TITLE
Frameworks not injecting?

### ISSUE THREAD

**Issue by HearseDev** [Al4ise/Azule#97]
I am trying to inject my tweak by the name of TwitchToolbox which comes with 3rd party frameworks inside layout/Library/Application\ Support/TweakName.bundle but azule does not import these frameworks in and does not edit the rpath. Is there any way you could add a way to add frameworks and also specify the rpath or automatically handle it for us? I am honestly not sure if it is doing it correctly because it does not say anything about importing frameworks in the log messages but it does import my bundle folder over to Twitch.app/Tweakname.bundle. Also my tweak has a custom rpath specified to the location /Library/Application\ Support/TweakName.bundle so i am just wondering if this is already worked out and maybe i am mistaken? or is this something you need to work out

**Comment by Al4ise** [comment]
Framework support is already there, but if i have to be honest, i didn't know frameworks could be inside .bundle files. Could you provide me with a .deb file of the tweak so I can do some testing?

**Comment by Al4ise** [comment]
Also, what exactly do you mean by 'specifying the loader_path'. I am not sure I understand

**Comment by HearseDev** [comment]
Update: I can get it to work perfectly once i put all the frameworks in the root of the layout folder. and specify TwitchToolbox_LDFLAGS += -rpath @loader_path/

**Comment by Al4ise** [comment]
should work in the latest update. it seems to work on my end but still, could you test it to confirm?

**Comment by HearseDev** [comment]
> should work in the latest update. it seems to work on my end but still, could you test it to confirm?

Can confirm, it works. Instead of copying the frameworks over from the bundle to Frameworks, might i suggest moving the frameworks instead?

**Comment by Al4ise** [comment]
Uh, i'm sorry, i'm not sure I understand again. Could you elaborate?

**Comment by HearseDev** [comment]
It broke again. Here is what you should be doing, 
1. Move XX.bundle to XXApp.app root
2. Move all frameworks from any sub directory in layout (XX.bundle in this case) to XXApp.app/Frameworks
3. Now, use install_name_tool to change the Tweak.dylib rpath for everything to @loader_path since Frameworks folder is the @loader_path for our tweak dylib. (This is important if the tweak author changed the rpath in their makefile)

**Comment by Al4ise** [comment]
Correct me if I'm wrong but isn't an rpath global to the whole app, not just for a specific dylib?

**Comment by Al4ise** [comment]
The current solution adds the .bundle as another rpath for the app so.. idk something tells me thats among the more correct ways to do the thing as it doesn't tamper with the integrity of .bundle files

**Comment by HearseDev** [comment]
> The current solution adds the .bundle as another rpath for the app so.. idk something tells me thats among the more correct ways to do the thing as it doesn't tamper with the integrity of .bundle files
Yes actually that sounds way more ideal for the situation but one of the issues i have been running across is that people that use sideloadly are complaining that the ipa unfortunately crashes. and the crash logs state that the dylib couldn't find the frameworks at the rpaths. So i am not sure what is happening but for the moment, i have a script that copies the frameworks to the root of layout and changes the rpath specification from my makefile to @loader_path. and then run azule, and that way has been working fine for people that use sideloadly. Not really sure what is the issue .

**Comment by Al4ise** [comment]
Well, I have some free time today so I'll look into it, but if it's a problem with sidealoadly only.. you know, every signing service has its own issues

**Comment by Al4ise** [comment]
Well I couldn't reproduce the issue on my end, but I fixed quite the serious issue with azule where it would wipe the app's entitlements so.. there's at least a small chance it may work for you now?

**Comment by dayanch96** [comment]
@HearseDev

**Comment by Al4ise** [comment]
please reopen if you still have issues

**Comment by dayanch96** [comment]
> please reopen if you still have issues

now i have issues with injecting frameworks directly using -f. azule just ignores it
