### ISSUE TITLE
azule is not injecting tweaks anymore

### ISSUE THREAD

**Issue by dobby1970** [Al4ise/Azule#98]
after the auto update today, every app I try to inject tweaks in is not working anymore. I hope there is a way to downgrade

**Comment by dayanch96** [comment]
agree, ignores dylibs, injects only frameworks

**Comment by Lizynz** [comment]
only one tweak can be sewn in, two are not added as before

**Comment by Al4ise** [comment]
uh shit, i’ll fix it by the end of the day

**Comment by Haxonate** [comment]
> uh shit, i’ll fix it by the end of the day

a fix is not ready yet?

**Comment by Al4ise** [comment]
fixed
